-- AlterTable
ALTER TABLE `restaurant` ADD COLUMN `cuisine` VARCHAR(191) NULL,
    ADD COLUMN `deliveryTime` VARCHAR(191) NULL,
    ADD COLUMN `distance` DOUBLE NULL,
    ADD COLUMN `hasOffer` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `imageUrl` VARCHAR(191) NULL,
    ADD COLUMN `isOpen` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `minOrder` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `offer` INTEGER NULL,
    ADD COLUMN `rating` DOUBLE NULL DEFAULT 0;
